export const CLASS_INCHARGES = {
  "CSE-6-A": {
    name: "Dr. Sarah Jenkins",
    designation: "Associate Professor & Class In-Charge",
    email: "sarah.jenkins@college.edu",
    phone: "+1 (555) 345-6789",
    cabin: "Block B, Room 302"
  },
  "CSE-6-B": {
    name: "Prof. Marcus Bell",
    designation: "Assistant Professor & Class In-Charge",
    email: "marcus.bell@college.edu",
    phone: "+1 (555) 345-6790",
    cabin: "Block B, Room 305"
  },
  "CSE-2-A": {
    name: "Dr. David Wilson",
    designation: "Professor & 1st Year In-Charge",
    email: "david.wilson@college.edu",
    phone: "+1 (555) 234-9911",
    cabin: "Block A, Room 104"
  },
  "CSE-4-A": {
    name: "Dr. Aris Thorne",
    designation: "Associate Professor & In-Charge",
    email: "aris.thorne@college.edu",
    phone: "+1 (555) 456-3388",
    cabin: "Block B, Room 210"
  },
  "ECE-4-A": {
    name: "Prof. Anita Sharma",
    designation: "Associate Professor & Class In-Charge",
    email: "anita.sharma@college.edu",
    phone: "+1 (555) 456-1122",
    cabin: "Block C, Room 201"
  },
  "MECH-8-A": {
    name: "Prof. Rajesh Kumar",
    designation: "Professor & HoD Mechanical",
    email: "rajesh.kumar@college.edu",
    phone: "+1 (555) 567-3344",
    cabin: "Block D, Room 401"
  },
  "CIVIL-4-A": {
    name: "Dr. Elena Gilbert",
    designation: "Associate Professor & In-Charge",
    email: "elena.gilbert@college.edu",
    phone: "+1 (555) 678-5566",
    cabin: "Block E, Room 102"
  },
  "IT-8-A": {
    name: "Dr. Nathan Drake",
    designation: "Associate Professor & HoD IT",
    email: "nathan.drake@college.edu",
    phone: "+1 (555) 789-4455",
    cabin: "Block B, Room 410"
  }
};

export const STUDENTS = [
  // ===================== 3RD YEAR (6TH SEMESTER) =====================
  {
    id: "STU202401",
    rollNo: "CS2024-042",
    name: "Alex Morgan",
    gender: "Female",
    email: "alex.morgan@college.edu",
    phone: "+1 (555) 234-5678",
    department: "Computer Science & Engineering",
    year: "3rd Year",
    semester: "6th Semester",
    section: "A",
    cgpa: 8.7,
    marksPercentage: 87.2,
    academicStanding: "Passed",
    backlogs: 0,
    classRank: 4,
    parentName: "Mr. David Morgan",
    parentPhone: "+1 (555) 876-5432",
    totalClasses: 182,
    attendedClasses: 148,
    attendanceRate: 81.3,
    status: "Good",
    classIncharge: CLASS_INCHARGES["CSE-6-A"]
  },
  {
    id: "STU202402",
    rollNo: "CS2024-001",
    name: "Aiden Scott",
    gender: "Male",
    email: "aiden.scott@college.edu",
    phone: "+1 (555) 101-2001",
    department: "Computer Science & Engineering",
    year: "3rd Year",
    semester: "6th Semester",
    section: "A",
    cgpa: 9.6,
    marksPercentage: 96.5,
    academicStanding: "Topper",
    backlogs: 0,
    classRank: 1,
    parentName: "Robert Scott",
    parentPhone: "+1 (555) 901-2001",
    totalClasses: 182,
    attendedClasses: 168,
    attendanceRate: 92.3,
    status: "Excellent",
    classIncharge: CLASS_INCHARGES["CSE-6-A"]
  },
  {
    id: "STU202403",
    rollNo: "CS2024-002",
    name: "Bella Chen",
    gender: "Female",
    email: "bella.chen@college.edu",
    phone: "+1 (555) 101-2002",
    department: "Computer Science & Engineering",
    year: "3rd Year",
    semester: "6th Semester",
    section: "A",
    cgpa: 9.2,
    marksPercentage: 92.0,
    academicStanding: "Topper",
    backlogs: 0,
    classRank: 2,
    parentName: "Wei Chen",
    parentPhone: "+1 (555) 901-2002",
    totalClasses: 182,
    attendedClasses: 158,
    attendanceRate: 86.8,
    status: "Good",
    classIncharge: CLASS_INCHARGES["CSE-6-A"]
  },
  {
    id: "STU202404",
    rollNo: "CS2024-003",
    name: "Caleb Johnson",
    gender: "Male",
    email: "caleb.johnson@college.edu",
    phone: "+1 (555) 101-2003",
    department: "Computer Science & Engineering",
    year: "3rd Year",
    semester: "6th Semester",
    section: "A",
    cgpa: 6.8,
    marksPercentage: 68.1,
    academicStanding: "Passed",
    backlogs: 0,
    classRank: 18,
    parentName: "Marcus Johnson",
    parentPhone: "+1 (555) 901-2003",
    totalClasses: 182,
    attendedClasses: 124,
    attendanceRate: 68.1,
    status: "Warning",
    classIncharge: CLASS_INCHARGES["CSE-6-A"]
  },
  {
    id: "STU202405",
    rollNo: "CS2024-004",
    name: "Daniel Diaz",
    gender: "Male",
    email: "daniel.diaz@college.edu",
    phone: "+1 (555) 101-2004",
    department: "Computer Science & Engineering",
    year: "3rd Year",
    semester: "6th Semester",
    section: "A",
    cgpa: 4.4,
    marksPercentage: 44.0,
    academicStanding: "Failed",
    backlogs: 2,
    classRank: 29,
    parentName: "Hector Diaz",
    parentPhone: "+1 (555) 901-2004",
    totalClasses: 182,
    attendedClasses: 112,
    attendanceRate: 61.5,
    status: "Critical",
    classIncharge: CLASS_INCHARGES["CSE-6-A"]
  },
  {
    id: "STU202406",
    rollNo: "CS2024-005",
    name: "Elena Rostova",
    gender: "Female",
    email: "elena.rostova@college.edu",
    phone: "+1 (555) 101-2005",
    department: "Computer Science & Engineering",
    year: "3rd Year",
    semester: "6th Semester",
    section: "A",
    cgpa: 9.0,
    marksPercentage: 90.4,
    academicStanding: "Topper",
    backlogs: 0,
    classRank: 3,
    parentName: "Igor Rostov",
    parentPhone: "+1 (555) 901-2005",
    totalClasses: 182,
    attendedClasses: 172,
    attendanceRate: 94.5,
    status: "Excellent",
    classIncharge: CLASS_INCHARGES["CSE-6-A"]
  },
  {
    id: "STU202411",
    rollNo: "CS2024-011",
    name: "Kevin Patel",
    gender: "Male",
    email: "kevin.patel@college.edu",
    phone: "+1 (555) 101-2011",
    department: "Computer Science & Engineering",
    year: "3rd Year",
    semester: "6th Semester",
    section: "A",
    cgpa: 4.1,
    marksPercentage: 41.5,
    academicStanding: "Failed",
    backlogs: 3,
    classRank: 30,
    parentName: "Sanjay Patel",
    parentPhone: "+1 (555) 901-2011",
    totalClasses: 182,
    attendedClasses: 104,
    attendanceRate: 57.1,
    status: "Critical",
    classIncharge: CLASS_INCHARGES["CSE-6-A"]
  },
  // Section B - 3rd Year
  {
    id: "STU202415",
    rollNo: "CS2024-061",
    name: "Oscar Wilde",
    gender: "Male",
    email: "oscar.wilde@college.edu",
    phone: "+1 (555) 101-2015",
    department: "Computer Science & Engineering",
    year: "3rd Year",
    semester: "6th Semester",
    section: "B",
    cgpa: 9.5,
    marksPercentage: 95.0,
    academicStanding: "Topper",
    backlogs: 0,
    classRank: 1,
    parentName: "Arthur Wilde",
    parentPhone: "+1 (555) 901-2015",
    totalClasses: 182,
    attendedClasses: 169,
    attendanceRate: 92.8,
    status: "Excellent",
    classIncharge: CLASS_INCHARGES["CSE-6-B"]
  },
  {
    id: "STU202416",
    rollNo: "CS2024-062",
    name: "Priya Sharma",
    gender: "Female",
    email: "priya.sharma@college.edu",
    phone: "+1 (555) 101-2016",
    department: "Computer Science & Engineering",
    year: "3rd Year",
    semester: "6th Semester",
    section: "B",
    cgpa: 8.3,
    marksPercentage: 83.5,
    academicStanding: "Passed",
    backlogs: 0,
    classRank: 5,
    parentName: "Rajesh Sharma",
    parentPhone: "+1 (555) 901-2016",
    totalClasses: 182,
    attendedClasses: 154,
    attendanceRate: 84.6,
    status: "Good",
    classIncharge: CLASS_INCHARGES["CSE-6-B"]
  },
  {
    id: "STU202417",
    rollNo: "CS2024-063",
    name: "Quinn Roberts",
    gender: "Non-binary",
    email: "quinn.roberts@college.edu",
    phone: "+1 (555) 101-2017",
    department: "Computer Science & Engineering",
    year: "3rd Year",
    semester: "6th Semester",
    section: "B",
    cgpa: 4.8,
    marksPercentage: 48.0,
    academicStanding: "Failed",
    backlogs: 1,
    classRank: 28,
    parentName: "Sarah Roberts",
    parentPhone: "+1 (555) 901-2017",
    totalClasses: 182,
    attendedClasses: 119,
    attendanceRate: 65.4,
    status: "Critical",
    classIncharge: CLASS_INCHARGES["CSE-6-B"]
  },

  // ===================== 1ST YEAR (1ST & 2ND SEMESTER) =====================
  {
    id: "STU202601",
    rollNo: "CS2026-001",
    name: "Lucas Vance",
    gender: "Male",
    email: "lucas.vance@college.edu",
    phone: "+1 (555) 888-1001",
    department: "Computer Science & Engineering",
    year: "1st Year",
    semester: "2nd Semester",
    section: "A",
    cgpa: 9.7,
    marksPercentage: 97.4,
    academicStanding: "Topper",
    backlogs: 0,
    classRank: 1,
    parentName: "William Vance",
    parentPhone: "+1 (555) 999-1001",
    totalClasses: 140,
    attendedClasses: 135,
    attendanceRate: 96.4,
    status: "Excellent",
    classIncharge: CLASS_INCHARGES["CSE-2-A"]
  },
  {
    id: "STU202602",
    rollNo: "CS2026-002",
    name: "Chloe Evans",
    gender: "Female",
    email: "chloe.evans@college.edu",
    phone: "+1 (555) 888-1002",
    department: "Computer Science & Engineering",
    year: "1st Year",
    semester: "2nd Semester",
    section: "A",
    cgpa: 8.4,
    marksPercentage: 84.1,
    academicStanding: "Passed",
    backlogs: 0,
    classRank: 6,
    parentName: "Benjamin Evans",
    parentPhone: "+1 (555) 999-1002",
    totalClasses: 140,
    attendedClasses: 115,
    attendanceRate: 82.1,
    status: "Good",
    classIncharge: CLASS_INCHARGES["CSE-2-A"]
  },
  {
    id: "STU202603",
    rollNo: "CS2026-003",
    name: "Brandon Murphy",
    gender: "Male",
    email: "brandon.murphy@college.edu",
    phone: "+1 (555) 888-1003",
    department: "Computer Science & Engineering",
    year: "1st Year",
    semester: "1st Semester",
    section: "B",
    cgpa: 4.6,
    marksPercentage: 46.2,
    academicStanding: "Failed",
    backlogs: 2,
    classRank: 32,
    parentName: "Dennis Murphy",
    parentPhone: "+1 (555) 999-1003",
    totalClasses: 140,
    attendedClasses: 94,
    attendanceRate: 67.1,
    status: "Critical",
    classIncharge: CLASS_INCHARGES["CSE-2-A"]
  },
  {
    id: "STU202604",
    rollNo: "EC2026-001",
    name: "Maya Lin",
    gender: "Female",
    email: "maya.lin@college.edu",
    phone: "+1 (555) 888-1004",
    department: "Electronics & Communication",
    year: "1st Year",
    semester: "2nd Semester",
    section: "A",
    cgpa: 9.3,
    marksPercentage: 93.0,
    academicStanding: "Topper",
    backlogs: 0,
    classRank: 1,
    parentName: "Ken Lin",
    parentPhone: "+1 (555) 999-1004",
    totalClasses: 140,
    attendedClasses: 129,
    attendanceRate: 92.1,
    status: "Excellent",
    classIncharge: CLASS_INCHARGES["CSE-2-A"]
  },

  // ===================== 2ND YEAR (3RD & 4TH SEMESTER) =====================
  {
    id: "STU202501",
    rollNo: "CS2025-001",
    name: "Julian Rivera",
    gender: "Male",
    email: "julian.rivera@college.edu",
    phone: "+1 (555) 777-2001",
    department: "Computer Science & Engineering",
    year: "2nd Year",
    semester: "4th Semester",
    section: "A",
    cgpa: 9.4,
    marksPercentage: 94.0,
    academicStanding: "Topper",
    backlogs: 0,
    classRank: 1,
    parentName: "Carlos Rivera",
    parentPhone: "+1 (555) 666-2001",
    totalClasses: 160,
    attendedClasses: 152,
    attendanceRate: 95.0,
    status: "Excellent",
    classIncharge: CLASS_INCHARGES["CSE-4-A"]
  },
  {
    id: "STU202502",
    rollNo: "CS2025-002",
    name: "Samantha Brooks",
    gender: "Female",
    email: "samantha.brooks@college.edu",
    phone: "+1 (555) 777-2002",
    department: "Computer Science & Engineering",
    year: "2nd Year",
    semester: "3rd Semester",
    section: "B",
    cgpa: 7.9,
    marksPercentage: 79.2,
    academicStanding: "Passed",
    backlogs: 0,
    classRank: 9,
    parentName: "Thomas Brooks",
    parentPhone: "+1 (555) 666-2002",
    totalClasses: 160,
    attendedClasses: 131,
    attendanceRate: 81.8,
    status: "Good",
    classIncharge: CLASS_INCHARGES["CSE-4-A"]
  },
  {
    id: "STU202503",
    rollNo: "EC2025-001",
    name: "Ethan Wright",
    gender: "Male",
    email: "ethan.wright@college.edu",
    phone: "+1 (555) 777-2003",
    department: "Electronics & Communication",
    year: "2nd Year",
    semester: "4th Semester",
    section: "A",
    cgpa: 4.3,
    marksPercentage: 43.1,
    academicStanding: "Failed",
    backlogs: 2,
    classRank: 27,
    parentName: "Gregory Wright",
    parentPhone: "+1 (555) 666-2003",
    totalClasses: 160,
    attendedClasses: 102,
    attendanceRate: 63.7,
    status: "Critical",
    classIncharge: CLASS_INCHARGES["ECE-4-A"]
  },
  {
    id: "STU202504",
    rollNo: "CE2025-001",
    name: "Avery Jackson",
    gender: "Female",
    email: "avery.jackson@college.edu",
    phone: "+1 (555) 777-2004",
    department: "Civil Engineering",
    year: "2nd Year",
    semester: "4th Semester",
    section: "A",
    cgpa: 8.6,
    marksPercentage: 86.4,
    academicStanding: "Passed",
    backlogs: 0,
    classRank: 3,
    parentName: "Paul Jackson",
    parentPhone: "+1 (555) 666-2004",
    totalClasses: 160,
    attendedClasses: 140,
    attendanceRate: 87.5,
    status: "Good",
    classIncharge: CLASS_INCHARGES["CIVIL-4-A"]
  },

  // ===================== 4TH YEAR (7TH & 8TH SEMESTER) =====================
  {
    id: "STU202301",
    rollNo: "CS2023-001",
    name: "Liam O'Connor",
    gender: "Male",
    email: "liam.oconnor@college.edu",
    phone: "+1 (555) 444-4001",
    department: "Computer Science & Engineering",
    year: "4th Year",
    semester: "8th Semester",
    section: "A",
    cgpa: 9.8,
    marksPercentage: 98.1,
    academicStanding: "Topper",
    backlogs: 0,
    classRank: 1,
    parentName: "Sean O'Connor",
    parentPhone: "+1 (555) 333-4001",
    totalClasses: 190,
    attendedClasses: 184,
    attendanceRate: 96.8,
    status: "Excellent",
    classIncharge: CLASS_INCHARGES["CSE-6-A"]
  },
  {
    id: "STU202302",
    rollNo: "ME2023-001",
    name: "Rohit Sharma",
    gender: "Male",
    email: "rohit.sharma@college.edu",
    phone: "+1 (555) 444-4002",
    department: "Mechanical Engineering",
    year: "4th Year",
    semester: "8th Semester",
    section: "A",
    cgpa: 7.8,
    marksPercentage: 78.5,
    academicStanding: "Passed",
    backlogs: 0,
    classRank: 7,
    parentName: "Anil Sharma",
    parentPhone: "+1 (555) 333-4002",
    totalClasses: 190,
    attendedClasses: 145,
    attendanceRate: 76.3,
    status: "Good",
    classIncharge: CLASS_INCHARGES["MECH-8-A"]
  },
  {
    id: "STU202303",
    rollNo: "ME2023-002",
    name: "Vikram Malhotra",
    gender: "Male",
    email: "vikram.malhotra@college.edu",
    phone: "+1 (555) 444-4003",
    department: "Mechanical Engineering",
    year: "4th Year",
    semester: "8th Semester",
    section: "A",
    cgpa: 4.7,
    marksPercentage: 47.0,
    academicStanding: "Failed",
    backlogs: 2,
    classRank: 26,
    parentName: "Karan Malhotra",
    parentPhone: "+1 (555) 333-4003",
    totalClasses: 190,
    attendedClasses: 110,
    attendanceRate: 57.8,
    status: "Critical",
    classIncharge: CLASS_INCHARGES["MECH-8-A"]
  },
  {
    id: "STU202304",
    rollNo: "IT2023-001",
    name: "Sophia Martinez",
    gender: "Female",
    email: "sophia.martinez@college.edu",
    phone: "+1 (555) 444-4004",
    department: "Information Technology",
    year: "4th Year",
    semester: "7th Semester",
    section: "B",
    cgpa: 9.1,
    marksPercentage: 91.5,
    academicStanding: "Topper",
    backlogs: 0,
    classRank: 2,
    parentName: "Ricardo Martinez",
    parentPhone: "+1 (555) 333-4004",
    totalClasses: 190,
    attendedClasses: 175,
    attendanceRate: 92.1,
    status: "Excellent",
    classIncharge: CLASS_INCHARGES["IT-8-A"]
  },
  {
    id: "STU202305",
    rollNo: "CV2023-001",
    name: "Henry Zhao",
    gender: "Male",
    email: "henry.zhao@college.edu",
    phone: "+1 (555) 444-4005",
    department: "Civil Engineering",
    year: "4th Year",
    semester: "8th Semester",
    section: "A",
    cgpa: 8.2,
    marksPercentage: 82.3,
    academicStanding: "Passed",
    backlogs: 0,
    classRank: 6,
    parentName: "Long Zhao",
    parentPhone: "+1 (555) 333-4005",
    totalClasses: 190,
    attendedClasses: 153,
    attendanceRate: 80.5,
    status: "Good",
    classIncharge: CLASS_INCHARGES["CIVIL-4-A"]
  }
];
