# Generated by Django 6.1.1 on 2026-09-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="attendance_rate",
            field=models.FloatField(default=80.0),
        ),
    ]
